/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Twitt;

import HOME.Desktop;
import java.awt.Component;
import static java.awt.Frame.MAXIMIZED_BOTH;
import java.awt.Image;
import java.io.File;
import java.io.IOException;
import java.lang.System.Logger;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.nio.file.StandardCopyOption;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Josue Gavidia
 */
public class X extends javax.swing.JInternalFrame {

    /**
     * Creates new form InicioSesion
     */
    Twitter Twitt = new Twitter();
    DefaultListModel<String> modeloLista = new DefaultListModel();
    boolean picSelected;

    public X() {

        initComponents();
        this.setSize(1611, 810);
        jPanel9.setVisible(false);
        jPanel6.setVisible(false);
        Paneñ.setVisible(false);
        explore.setVisible(false);
        interactions.setVisible(false);
        profile.setVisible(false);
        logout.setVisible(false);
        jPanel8.setVisible(false);
        home.setVisible(false);
        Login.setVisible(true);
        Registro.setVisible(false);
        LISTA.setVisible(false);
        picSelected = false;
        try {
            initTimeline();
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }

    public void initTimeline() throws IOException {
        Twitt.mostrarTwitsGlobales(Timeline);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        USER = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        loginNEXT = new javax.swing.JButton();
        SIGN_IN = new javax.swing.JButton();
        PASS = new javax.swing.JPasswordField();
        mostrar_contra = new javax.swing.JCheckBox();
        Registro = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        FULLNAME = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        GENDER = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        USERNAME = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        PASSWORD = new javax.swing.JTextField();
        AGE = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        NEXT_REGISTRO = new javax.swing.JButton();
        logOPTIONregistro = new javax.swing.JButton();
        ProfilePictureSelection = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        primerito = new javax.swing.JTabbedPane();
        Paneñ = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        home = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        PostTwit = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        FypPic = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        Timeline = new javax.swing.JTextArea();
        jLabel15 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        explore = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        searchBar = new javax.swing.JTextField();
        SELECT = new javax.swing.JButton();
        ContainerLISTA = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        LISTA = new javax.swing.JList<>();
        profileBUSCADO = new javax.swing.JPanel();
        profilePicExplore = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        profileNameExplore = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        profileDateJoinedExplore = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        profileGenderExplore = new javax.swing.JLabel();
        profileAgeExplore = new javax.swing.JLabel();
        profileFollowersCountExplore = new javax.swing.JLabel();
        profileFollowingCountExplore = new javax.swing.JLabel();
        Follow_Unfollow = new javax.swing.JButton();
        refreshExplore = new javax.swing.JButton();
        interactions = new javax.swing.JPanel();
        profile = new javax.swing.JPanel();
        profilePic = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        profileName = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        profileDateJoined = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        profileGender = new javax.swing.JLabel();
        profileAge = new javax.swing.JLabel();
        profileFollowersCount = new javax.swing.JLabel();
        profileFollowingCount = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        refreshPROFILE = new javax.swing.JButton();
        logout = new javax.swing.JPanel();
        jLabel41 = new javax.swing.JLabel();
        XLOGOUT = new javax.swing.JToggleButton();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jTextField2 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();

        setClosable(true);
        setPreferredSize(new java.awt.Dimension(1621, 847));
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosed(evt);
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Login.setBackground(new java.awt.Color(0, 0, 0));
        Login.setPreferredSize(new java.awt.Dimension(1610, 810));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Login");
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username:");
        Login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 140, -1, -1));

        USER.setBackground(new java.awt.Color(0, 0, 0));
        USER.setForeground(new java.awt.Color(255, 255, 255));
        USER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERActionPerformed(evt);
            }
        });
        Login.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 140, 290, 40));

        jLabel3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password:");
        Login.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("You don't have an accout yet? ");
        Login.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 360, -1, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TwittImages/logo.jpg"))); // NOI18N
        jLabel6.setText("Logo");
        Login.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 610, 570));

        loginNEXT.setBackground(new java.awt.Color(0, 102, 255));
        loginNEXT.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        loginNEXT.setForeground(new java.awt.Color(255, 255, 255));
        loginNEXT.setText("Next");
        loginNEXT.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        loginNEXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginNEXTActionPerformed(evt);
            }
        });
        Login.add(loginNEXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 580, 150, 50));

        SIGN_IN.setBackground(new java.awt.Color(0, 0, 0));
        SIGN_IN.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        SIGN_IN.setForeground(new java.awt.Color(0, 102, 255));
        SIGN_IN.setText("Sign in now!");
        SIGN_IN.setBorder(null);
        SIGN_IN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SIGN_INActionPerformed(evt);
            }
        });
        Login.add(SIGN_IN, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 350, 240, 40));

        PASS.setBackground(new java.awt.Color(0, 0, 0));
        PASS.setForeground(new java.awt.Color(255, 255, 255));
        PASS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        Login.add(PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 220, 290, 40));

        mostrar_contra.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        mostrar_contra.setForeground(new java.awt.Color(255, 255, 255));
        mostrar_contra.setText("Show Password");
        mostrar_contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mostrar_contraActionPerformed(evt);
            }
        });
        Login.add(mostrar_contra, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 220, 40));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 810));

        Registro.setBackground(new java.awt.Color(0, 0, 0));
        Registro.setPreferredSize(new java.awt.Dimension(1430, 810));
        Registro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Create your account");
        Registro.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Full Name:");
        Registro.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 110, -1, -1));

        FULLNAME.setBackground(new java.awt.Color(0, 0, 0));
        FULLNAME.setForeground(new java.awt.Color(255, 255, 255));
        FULLNAME.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        Registro.add(FULLNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 100, 460, 40));

        jLabel8.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Gender:");
        Registro.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        GENDER.setBackground(new java.awt.Color(0, 0, 0));
        GENDER.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        GENDER.setForeground(new java.awt.Color(255, 255, 255));
        GENDER.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M" }));
        GENDER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        Registro.add(GENDER, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 160, -1, -1));

        jLabel9.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Username:");
        Registro.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, -1, -1));

        USERNAME.setBackground(new java.awt.Color(0, 0, 0));
        USERNAME.setForeground(new java.awt.Color(255, 255, 255));
        USERNAME.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        Registro.add(USERNAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 220, 460, 40));

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Password:");
        Registro.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, -1, -1));

        jLabel11.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Age:");
        Registro.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 340, -1, -1));

        jLabel12.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("You already have an account?");
        Registro.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 410, -1, -1));

        PASSWORD.setBackground(new java.awt.Color(0, 0, 0));
        PASSWORD.setForeground(new java.awt.Color(255, 255, 255));
        PASSWORD.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        Registro.add(PASSWORD, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 460, 40));

        AGE.setBackground(new java.awt.Color(0, 0, 0));
        AGE.setForeground(new java.awt.Color(255, 255, 255));
        AGE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        AGE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AGEActionPerformed(evt);
            }
        });
        Registro.add(AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 340, 100, 40));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/TwittImages/logo.jpg"))); // NOI18N
        Registro.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 650, 580));

        NEXT_REGISTRO.setBackground(new java.awt.Color(0, 102, 255));
        NEXT_REGISTRO.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        NEXT_REGISTRO.setForeground(new java.awt.Color(255, 255, 255));
        NEXT_REGISTRO.setText("Next");
        NEXT_REGISTRO.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        NEXT_REGISTRO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NEXT_REGISTROActionPerformed(evt);
            }
        });
        Registro.add(NEXT_REGISTRO, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 550, 100, 50));

        logOPTIONregistro.setBackground(new java.awt.Color(0, 0, 0));
        logOPTIONregistro.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        logOPTIONregistro.setForeground(new java.awt.Color(0, 102, 255));
        logOPTIONregistro.setText("Login");
        logOPTIONregistro.setBorder(null);
        logOPTIONregistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOPTIONregistroActionPerformed(evt);
            }
        });
        Registro.add(logOPTIONregistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 410, 140, 40));

        ProfilePictureSelection.setBackground(new java.awt.Color(0, 102, 255));
        ProfilePictureSelection.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        ProfilePictureSelection.setForeground(new java.awt.Color(255, 255, 255));
        ProfilePictureSelection.setText("Choose Profile Picture");
        ProfilePictureSelection.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ProfilePictureSelection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProfilePictureSelectionActionPerformed(evt);
            }
        });
        Registro.add(ProfilePictureSelection, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, -1, -1));

        getContentPane().add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1610, 810));

        jPanel9.setBackground(new java.awt.Color(0, 0, 0));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        primerito.setBackground(new java.awt.Color(0, 0, 0));
        primerito.setForeground(new java.awt.Color(255, 255, 255));
        primerito.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        primerito.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        primerito.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                primeritoMouseClicked(evt);
            }
        });

        Paneñ.setBackground(new java.awt.Color(0, 0, 0));
        Paneñ.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane2.setBackground(new java.awt.Color(0, 0, 0));
        jTabbedPane2.setForeground(new java.awt.Color(255, 255, 255));
        jTabbedPane2.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N

        home.setBackground(new java.awt.Color(0, 0, 0));
        home.setPreferredSize(new java.awt.Dimension(784, 752));
        home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("What's happening?");
        home.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(364, 6, -1, -1));

        PostTwit.setBackground(new java.awt.Color(0, 0, 0));
        PostTwit.setColumns(20);
        PostTwit.setForeground(new java.awt.Color(63, 99, 139));
        PostTwit.setRows(5);
        PostTwit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        jScrollPane1.setViewportView(PostTwit);

        home.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(116, 39, 668, 111));

        jButton5.setBackground(new java.awt.Color(0, 102, 255));
        jButton5.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(255, 255, 255));
        jButton5.setText("Post");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        home.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(684, 156, 100, 30));

        FypPic.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255), 5));
        home.add(FypPic, new org.netbeans.lib.awtextra.AbsoluteConstraints(4, 6, 98, 85));

        Timeline.setEditable(false);
        Timeline.setBackground(new java.awt.Color(0, 0, 0));
        Timeline.setColumns(20);
        Timeline.setForeground(new java.awt.Color(255, 255, 255));
        Timeline.setRows(5);
        Timeline.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 255), 5, true));
        jScrollPane2.setViewportView(Timeline);

        home.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 710, 360));

        jLabel15.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Time Line ");
        home.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 180, -1, -1));

        jTabbedPane2.addTab("For you", home);

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 599, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Following", jPanel8);

        Paneñ.add(jTabbedPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 630));

        primerito.addTab("Home", Paneñ);

        explore.setBackground(new java.awt.Color(0, 0, 0));
        explore.setForeground(new java.awt.Color(0, 0, 0));
        explore.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        explore.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel17.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setText("Search");
        explore.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        searchBar.setBackground(new java.awt.Color(0, 0, 0));
        searchBar.setForeground(new java.awt.Color(255, 255, 255));
        searchBar.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        searchBar.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                searchBarFocusLost(evt);
            }
        });
        searchBar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBarMouseClicked(evt);
            }
        });
        searchBar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBarActionPerformed(evt);
            }
        });
        searchBar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                searchBarKeyTyped(evt);
            }
        });
        explore.add(searchBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 540, 40));

        SELECT.setText("Select");
        SELECT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SELECTActionPerformed(evt);
            }
        });
        explore.add(SELECT, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 20, 110, 40));

        ContainerLISTA.setBackground(new java.awt.Color(0, 0, 0));
        ContainerLISTA.setLayout(new java.awt.BorderLayout());

        LISTA.setBackground(new java.awt.Color(153, 153, 153));
        LISTA.setBorder(null);
        LISTA.setForeground(new java.awt.Color(0, 0, 0));
        LISTA.setSelectionForeground(new java.awt.Color(153, 204, 255));
        jScrollPane4.setViewportView(LISTA);

        ContainerLISTA.add(jScrollPane4, java.awt.BorderLayout.CENTER);

        explore.add(ContainerLISTA, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 60, 540, 80));

        profileBUSCADO.setBackground(new java.awt.Color(0, 0, 0));
        profileBUSCADO.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilePicExplore.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        profileBUSCADO.add(profilePicExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 240, 200));

        jLabel20.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setText("Name:");
        profileBUSCADO.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, -1, -1));

        profileNameExplore.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileNameExplore.setForeground(new java.awt.Color(255, 255, 255));
        profileNameExplore.setText("jLabel15");
        profileBUSCADO.add(profileNameExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 30, -1, -1));

        jLabel22.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Joined on");
        profileBUSCADO.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 70, -1, -1));

        profileDateJoinedExplore.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileDateJoinedExplore.setForeground(new java.awt.Color(255, 255, 255));
        profileDateJoinedExplore.setText("jLabel17");
        profileBUSCADO.add(profileDateJoinedExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 70, -1, -1));

        jLabel28.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(255, 255, 255));
        jLabel28.setText("Gender:");
        profileBUSCADO.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 100, -1, -1));

        jLabel29.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(255, 255, 255));
        jLabel29.setText("Age:");
        profileBUSCADO.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, -1, -1));

        jLabel30.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Followers:");
        profileBUSCADO.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 180, -1, -1));

        jLabel31.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Following:");
        profileBUSCADO.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, -1, -1));

        profileGenderExplore.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileGenderExplore.setForeground(new java.awt.Color(255, 255, 255));
        profileGenderExplore.setText("jLabel23");
        profileBUSCADO.add(profileGenderExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        profileAgeExplore.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileAgeExplore.setForeground(new java.awt.Color(255, 255, 255));
        profileAgeExplore.setText("jLabel24");
        profileBUSCADO.add(profileAgeExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 140, -1, -1));

        profileFollowersCountExplore.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileFollowersCountExplore.setForeground(new java.awt.Color(255, 255, 255));
        profileFollowersCountExplore.setText("0");
        profileBUSCADO.add(profileFollowersCountExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 180, -1, -1));

        profileFollowingCountExplore.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileFollowingCountExplore.setForeground(new java.awt.Color(255, 255, 255));
        profileFollowingCountExplore.setText("0");
        profileBUSCADO.add(profileFollowingCountExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 30, -1));

        Follow_Unfollow.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Follow_UnfollowActionPerformed(evt);
            }
        });
        profileBUSCADO.add(Follow_Unfollow, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 90, 120, 40));

        explore.add(profileBUSCADO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 770, 620));

        refreshExplore.setText("Refresh");
        refreshExplore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshExploreActionPerformed(evt);
            }
        });
        explore.add(refreshExplore, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 80, 80, 60));

        primerito.addTab("Explore", explore);

        interactions.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout interactionsLayout = new javax.swing.GroupLayout(interactions);
        interactions.setLayout(interactionsLayout);
        interactionsLayout.setHorizontalGroup(
            interactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );
        interactionsLayout.setVerticalGroup(
            interactionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 810, Short.MAX_VALUE)
        );

        primerito.addTab("Interactions", interactions);

        profile.setBackground(new java.awt.Color(0, 0, 0));
        profile.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        profilePic.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        profile.add(profilePic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 240, 200));

        jLabel19.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(255, 255, 255));
        jLabel19.setText("Name:");
        profile.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 64, -1, -1));

        profileName.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileName.setForeground(new java.awt.Color(255, 255, 255));
        profileName.setText("jLabel15");
        profile.add(profileName, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel21.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(255, 255, 255));
        jLabel21.setText("Joined on");
        profile.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 103, -1, -1));

        profileDateJoined.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileDateJoined.setForeground(new java.awt.Color(255, 255, 255));
        profileDateJoined.setText("jLabel17");
        profile.add(profileDateJoined, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, -1, -1));

        jLabel23.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setText("Gender:");
        profile.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 142, -1, -1));

        jLabel24.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(255, 255, 255));
        jLabel24.setText("Age:");
        profile.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(303, 181, -1, -1));

        jLabel25.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(255, 255, 255));
        jLabel25.setText("Followers:");
        profile.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 220, -1, -1));

        jLabel26.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(255, 255, 255));
        jLabel26.setText("Following:");
        profile.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 220, -1, -1));

        jLabel27.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(255, 255, 255));
        jLabel27.setText("My Tweets");
        profile.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        profileGender.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileGender.setForeground(new java.awt.Color(255, 255, 255));
        profileGender.setText("jLabel23");
        profile.add(profileGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 140, -1, -1));

        profileAge.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileAge.setForeground(new java.awt.Color(255, 255, 255));
        profileAge.setText("jLabel24");
        profile.add(profileAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 180, -1, -1));

        profileFollowersCount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileFollowersCount.setForeground(new java.awt.Color(255, 255, 255));
        profileFollowersCount.setText("0");
        profile.add(profileFollowersCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, -1, -1));

        profileFollowingCount.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        profileFollowingCount.setForeground(new java.awt.Color(255, 255, 255));
        profileFollowingCount.setText("0");
        profile.add(profileFollowingCount, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 30, -1));

        jLabel32.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 36)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("MyProfile");
        profile.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        profile.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 260, 790, 30));

        refreshPROFILE.setText("Refresh");
        refreshPROFILE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshPROFILEActionPerformed(evt);
            }
        });
        profile.add(refreshPROFILE, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 10, 100, 30));

        primerito.addTab("Profile", profile);

        logout.setBackground(new java.awt.Color(0, 0, 0));
        logout.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel41.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel41.setForeground(new java.awt.Color(255, 255, 255));
        jLabel41.setText("Desea Cerrar Sesion?");
        logout.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(212, 46, -1, -1));

        XLOGOUT.setText("Continuar");
        XLOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XLOGOUTActionPerformed(evt);
            }
        });
        logout.add(XLOGOUT, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 175, -1, -1));

        primerito.addTab(" Log Out", logout);

        jPanel9.add(primerito, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 0, 930, 810));
        jPanel9.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 6, 40, 30));
        jPanel9.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, 40, 30));
        jPanel9.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 74, 40, 30));
        jPanel9.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 104, -1, 30));
        jPanel9.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 40, 20));

        getContentPane().add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 810));

        jPanel6.setBackground(new java.awt.Color(0, 0, 0));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel38.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Search");
        jPanel6.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 45, -1, -1));
        jPanel6.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));

        jLabel40.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 24)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Trends");
        jPanel6.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, -1, -1));

        jTextArea3.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea3.setColumns(20);
        jTextArea3.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jTextArea3.setForeground(new java.awt.Color(255, 255, 255));
        jTextArea3.setRows(5);
        jScrollPane3.setViewportView(jTextArea3);

        jPanel6.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 440, 341));

        jTextField2.setBackground(new java.awt.Color(0, 0, 0));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 102, 255), 4, true));
        jPanel6.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 40, 350, 30));

        jSeparator1.setBackground(new java.awt.Color(0, 0, 0));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel6.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 3, 30, 630));

        getContentPane().add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 0, 540, 810));

        getAccessibleContext().setAccessibleName("Twit");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERActionPerformed

    private void loginNEXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginNEXTActionPerformed
        if(!USER.getText().isEmpty()||!PASS.getText().isEmpty()){
        try {
            if (Twitt.iniciarSesion(USER.getText(), PASS.getText())) {

                System.out.println("ACCESS GRANTED");

                setHomePageVisibleTrue();
                //Setear el perfil
                setMyPfp(USER.getText(), profilePic);
                setMyMiniPfp(USER.getText(), FypPic);
                profileName.setText(Twitt.usuarioEnSesion.getNombreCompleto());
                setearFechaProfile();
                setearGeneroProfile();
                profileFollowersCount.setText(Twitt.getSeguidores(Twitt.usuarioEnSesion.getUsername()) + "");
                profileFollowingCount.setText(Twitt.getSeguidos(Twitt.usuarioEnSesion.getUsername()) + "");
                profileAge.setText(Twitt.usuarioEnSesion.getAge() + "");
                LISTA.setVisible(false);

            } else {
                JOptionPane.showMessageDialog(null, "Usuario o contraseña invalidos");
                System.out.println("NO ACCESS");
            }
        } catch (IOException ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
            System.out.println(ex.getCause());
        }
        }else{
            JOptionPane.showMessageDialog(null, "Llenar todos los campos");
        }

    }//GEN-LAST:event_loginNEXTActionPerformed

    private void SIGN_INActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SIGN_INActionPerformed
        Login.setVisible(false);
        Registro.setVisible(true);
    }//GEN-LAST:event_SIGN_INActionPerformed

    private void mostrar_contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mostrar_contraActionPerformed
        if (mostrar_contra.isSelected()) {
            PASS.setEchoChar((char) 0);
        } else {
            PASS.setEchoChar('*');
        }
    }//GEN-LAST:event_mostrar_contraActionPerformed

    private void AGEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AGEActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AGEActionPerformed

    private void NEXT_REGISTROActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NEXT_REGISTROActionPerformed
        if (!USERNAME.getText().isEmpty()&&picSelected) {
            char gender;
            int edad = Integer.parseInt(AGE.getText());
            if (GENDER.getSelectedIndex() == 0) {
                gender = 'F';

            } else {
                gender = 'M';
            }

            try {

                if (Twitt.crearCuenta(FULLNAME.getText(), USERNAME.getText(), PASSWORD.getText(), gender, edad)) {
                    Registro.setVisible(false);
                    Login.setVisible(true);
                } else {
                    JOptionPane.showMessageDialog(this, "Ha ocurrido un error al crear la cuenta");
                }

            } catch (IOException ex) {
                System.out.println(ex.getCause());
            }
        }else{
            JOptionPane.showMessageDialog(null, "Debe llenar todos los campos primero");
        }
    }//GEN-LAST:event_NEXT_REGISTROActionPerformed

    private void logOPTIONregistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOPTIONregistroActionPerformed
        Login.setVisible(true);
        Registro.setVisible(false);
    }//GEN-LAST:event_logOPTIONregistroActionPerformed

    private void ProfilePictureSelectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ProfilePictureSelectionActionPerformed
picSelected = true;
        try {
            elegirPfp(USERNAME.getText());
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(X.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_ProfilePictureSelectionActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            // TODO add your handling code here:
            Twitt.escribirTwit(Twitt.usuarioEnSesion.getUsername(), PostTwit.getText());
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
        try {
            Twitt.mostrarTwitsGlobales(Timeline);
        } catch (IOException ex) {
            java.util.logging.Logger.getLogger(X.class.getName()).log(Level.SEVERE, null, ex);
        }
        PostTwit.setText("");
    }//GEN-LAST:event_jButton5ActionPerformed

    private void XLOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XLOGOUTActionPerformed
        Twitt.cerrarSesion();
        visualLogout();
    }//GEN-LAST:event_XLOGOUTActionPerformed

    private void primeritoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_primeritoMouseClicked

    }//GEN-LAST:event_primeritoMouseClicked

    private void searchBarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBarActionPerformed

    }//GEN-LAST:event_searchBarActionPerformed

    private void searchBarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBarMouseClicked
        LISTA.setVisible(true);
    }//GEN-LAST:event_searchBarMouseClicked

    private void searchBarKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_searchBarKeyTyped
        if (!searchBar.getText().isEmpty()) {
            ContainerLISTA.setVisible(true);

        } else {
            ContainerLISTA.setVisible(false);

        }

        try {
            if (!searchBar.getText().isEmpty()) {
                Twitt.buscarListaUsuarios(LISTA, searchBar.getText());
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_searchBarKeyTyped

    private void searchBarFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_searchBarFocusLost

    }//GEN-LAST:event_searchBarFocusLost

    private void SELECTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SELECTActionPerformed

        Twitt.getSelectedUser(LISTA);
        System.out.println("Arriba isEmpty");
        if (!searchBar.getText().isEmpty()) {
            profileBUSCADO.setVisible(true);
            System.out.println("Afuera try");
            try {
                System.out.println("Adentro try");

                Twitt.setDatosUserBuscado(LISTA, profileNameExplore,
                        profileDateJoinedExplore, profileGenderExplore,
                        profileAgeExplore, profileFollowersCountExplore,
                        profileFollowingCountExplore, profilePicExplore);
                System.out.println("Datos seteados");

                if (Twitt.loSigo(Twitt.usuarioEnSesion.getUsername(), Twitt.userBuscado)) {
                    Follow_Unfollow.setText("Unfollow");
                    System.out.println("Boton unfollow");
                } else {
                    Follow_Unfollow.setText("Follow");
                    System.out.println("Boton Follow");
                }

            } catch (Exception ex) {
                ex.printStackTrace();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Llene ek campo de busqueda");
        }

        searchBar.setText("");

        ContainerLISTA.setVisible(false);
    }//GEN-LAST:event_SELECTActionPerformed

    private void Follow_UnfollowActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Follow_UnfollowActionPerformed
        try {
            if (Follow_Unfollow.getText().equals("Follow")) {

                Twitt.follow(Twitt.userBuscado, Twitt.usuarioEnSesion.getUsername());
                Follow_Unfollow.setText("Unfollow");

            } else {
                Twitt.unfollow(Twitt.userBuscado, Twitt.usuarioEnSesion.getUsername());
                Follow_Unfollow.setText("Follow");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

//try {
//       
//            
////            if (Twitt.loSigo(Twitt.usuarioEnSesion.getUsername(), Twitt.userBuscado)) {
////                Twitt.unfollow(Twitt.userBuscado, Twitt.usuarioEnSesion.getUsername());
////            } else {
////                Twitt.follow(Twitt.userBuscado, Twitt.usuarioEnSesion.getUsername());
////            }
//        } catch (IOException ex) {
//            System.out.println(ex.getMessage());
//        }
    }//GEN-LAST:event_Follow_UnfollowActionPerformed

    private void refreshExploreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshExploreActionPerformed

        Twitt.getSelectedUser(LISTA);
        try {
            Twitt.setDatosUserBuscado(LISTA, profileNameExplore,
                    profileDateJoinedExplore, profileGenderExplore,
                    profileAgeExplore, profileFollowersCountExplore,
                    profileFollowingCountExplore, profilePicExplore);
        } catch (IOException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_refreshExploreActionPerformed

    private void refreshPROFILEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshPROFILEActionPerformed
        try {

            profileFollowersCount.setText(Twitt.getSeguidores(Twitt.usuarioEnSesion.getUsername()) + "");
            profileFollowingCount.setText(Twitt.getSeguidos(Twitt.usuarioEnSesion.getUsername()) + "");
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_refreshPROFILEActionPerformed

    private void formInternalFrameClosed(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosed
        Desktop.twitAdded = true;
        Desktop.contBotonTwit++;
    }//GEN-LAST:event_formInternalFrameClosed

    public void setHomePageVisibleTrue() {
        jPanel9.setVisible(true);
        jPanel6.setVisible(true);
        Paneñ.setVisible(true);
        explore.setVisible(true);
        interactions.setVisible(true);
        profile.setVisible(true);
        logout.setVisible(true);
        jPanel8.setVisible(true);
        home.setVisible(true);
        Registro.setVisible(false);
        Login.setVisible(false);
        LISTA.setVisible(false);
        ContainerLISTA.setVisible(false);
        profileBUSCADO.setVisible(false);
    }

    public void visualLogout() {
        setHomePageVisibleFalse();
        Login.setVisible(true);
    }

    public void setHomePageVisibleFalse() {
        jPanel9.setVisible(false);
        jPanel6.setVisible(false);
        Paneñ.setVisible(false);
        explore.setVisible(false);
        interactions.setVisible(false);
        profile.setVisible(false);
        logout.setVisible(false);
        jPanel8.setVisible(false);
        home.setVisible(false);

    }

    public void setearFechaProfile() {
        long rawDate = Twitt.usuarioEnSesion.getLoginDate();
        Date loginDate = new Date(rawDate);
        SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String formateado = sdf.format(loginDate);
        profileDateJoined.setText(formateado);
    }

    public void setearGeneroProfile() {
        if (Twitt.usuarioEnSesion.getGender() == 'M') {
            profileGender.setText("Male");
        } else {
            profileGender.setText("Female");
        }
    }

    public void elegirPfp(String user) throws Exception {

        JFileChooser choose = new JFileChooser("Z\\" + Desktop.LoggedUser + "\\Imagenes");

        choose.setFileSelectionMode(JFileChooser.FILES_ONLY);
        choose.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("images", "png", "jpg",
                "jpeg"));
        int result = choose.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = choose.getSelectedFile();
            if (selectedFile.getName().toLowerCase().endsWith(".png") || selectedFile.getName().toLowerCase().endsWith(".jpg")
                    || selectedFile.getName().toLowerCase().endsWith(".jpeg")) {
                String sourcePath = selectedFile.getAbsolutePath();
                String destinoPath = "twitter/FotosDePerfil/" + user + ".jpg";
                try {
                    Path origen = selectedFile.toPath();
                    Path destino = Paths.get(destinoPath);
                    Files.move(origen, destino, StandardCopyOption.REPLACE_EXISTING);
//                    File original = new File(destinoPath);
//                    File rename = new File("twitter/FotosDePerfil/" + user + ".jpg");
//                    boolean renamed = original.renameTo(rename);
//                    if (renamed) {
//                        System.out.println("SE PUDO ALIMENTAR LA BASE DE DATOS PFP");
//                    } else {
//                        System.out.println("TRONO");
//                    }

                } catch (IOException e) {
                    System.out.println(e.getMessage());
                }
            }
        }
    }
    //UTILITARIAS

    public static void setMyMiniPfp(String usuario, JLabel label) {
        setMyPfp(usuario, label);
    }

    public static void setMyPfp(String usuario, JLabel label) {
        try {

            ImageIcon icon = new ImageIcon("twitter\\FotosDePerfil\\" + usuario + ".jpg");
            Image image = icon.getImage();

            Image scaledImage = image.getScaledInstance(label.getWidth(), label.getHeight(), Image.SCALE_SMOOTH);
            ImageIcon scaledIcon = new ImageIcon(scaledImage);

            label.setIcon(scaledIcon);

        } catch (Exception e) {
            e.printStackTrace();
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AGE;
    private javax.swing.JPanel ContainerLISTA;
    private javax.swing.JTextField FULLNAME;
    private javax.swing.JButton Follow_Unfollow;
    private javax.swing.JLabel FypPic;
    private javax.swing.JComboBox<String> GENDER;
    private javax.swing.JList<String> LISTA;
    private javax.swing.JPanel Login;
    private javax.swing.JButton NEXT_REGISTRO;
    private javax.swing.JPasswordField PASS;
    private javax.swing.JTextField PASSWORD;
    private javax.swing.JPanel Paneñ;
    private javax.swing.JTextArea PostTwit;
    private javax.swing.JButton ProfilePictureSelection;
    private javax.swing.JPanel Registro;
    private javax.swing.JButton SELECT;
    private javax.swing.JButton SIGN_IN;
    private javax.swing.JTextArea Timeline;
    private javax.swing.JTextField USER;
    private javax.swing.JTextField USERNAME;
    private javax.swing.JToggleButton XLOGOUT;
    private javax.swing.JPanel explore;
    private javax.swing.JPanel home;
    private javax.swing.JPanel interactions;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JButton logOPTIONregistro;
    private javax.swing.JButton loginNEXT;
    private javax.swing.JPanel logout;
    private javax.swing.JCheckBox mostrar_contra;
    private javax.swing.JTabbedPane primerito;
    private javax.swing.JPanel profile;
    private javax.swing.JLabel profileAge;
    private javax.swing.JLabel profileAgeExplore;
    private javax.swing.JPanel profileBUSCADO;
    private javax.swing.JLabel profileDateJoined;
    private javax.swing.JLabel profileDateJoinedExplore;
    private javax.swing.JLabel profileFollowersCount;
    private javax.swing.JLabel profileFollowersCountExplore;
    private javax.swing.JLabel profileFollowingCount;
    private javax.swing.JLabel profileFollowingCountExplore;
    private javax.swing.JLabel profileGender;
    private javax.swing.JLabel profileGenderExplore;
    private javax.swing.JLabel profileName;
    private javax.swing.JLabel profileNameExplore;
    private javax.swing.JLabel profilePic;
    private javax.swing.JLabel profilePicExplore;
    private javax.swing.JButton refreshExplore;
    private javax.swing.JButton refreshPROFILE;
    private javax.swing.JTextField searchBar;
    // End of variables declaration//GEN-END:variables
}
