/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HOME;

import BRAIN.FolderManager;
import Explorador.ExploradorDeArchivos;
import Programitas.CrearUs;
import ReproductorMusical.SoundPlayer;
import EditorTexto.Editortexto;
import CMD.cmd;
import Twitt.InstalarTwitter;
import Twitt.X;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Visualizador.Medias;

import java.awt.event.ActionEvent;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.Timer;

/**
 *
 * @author Josue Gavidia
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Fancy
     */
    //VARIABLES DE ESTA CLASE   
    public static String LoggedUser;
    public static String newUser;
    public static String pass;
    public static boolean filesAdded;
    public static boolean tunesAdded;
    public static boolean userCreated;
    public static boolean wordAdded;
    public static boolean cmdAdded;
    public static boolean imagesAdded;
    public static boolean twitAdded;
    public static int refresh = 0;
    public static String nombre;
    FolderManager L = new FolderManager(LoggedUser);
    int contBotonWin = 2;
    public static int contBotonCmd = 2;
    public static int contBotonFiles = 2;
    public static int contBotonJtunes = 2;
    public static int contBotonWord = 2;
    public static int contBotonImages = 2;
    public static int contBotonTwit = 2;
    SoundPlayer tunes;
    ExploradorDeArchivos files;
    CrearUs create;
    Editortexto word;
    Medias img;
    cmd Cmd;
    
    InstalarTwitter dock;

    public Desktop() throws IOException {

        filesAdded = true;
        tunesAdded = true;
        userCreated = true;
        wordAdded = true;
        cmdAdded = true;
        imagesAdded = true;
        twitAdded = true;
        Cmd = new cmd();
        tunes = new SoundPlayer();
        files = new ExploradorDeArchivos();
        create = new CrearUs();
        word = new Editortexto();
        img = new Medias();
        
        dock = new InstalarTwitter();

        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        L.CrearZyAdmin();
        this.setLocationRelativeTo(null);
        WholeDesktop.setVisible(false);

        WholeDesktop.setSize(1920, 1080);
        Login.setVisible(true);
        Login.setSize(1920, 1080);

        tunes.setVisible(false);

        OPCWINBUTTON.setVisible(false);
        actualizarHora();
        actualizarFecha();
    }
    
    X twit = new X();

    //FIN DEL MP3
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        WholeDesktop = new javax.swing.JDesktopPane();
        BarraTareas = new javax.swing.JPanel();
        FILES = new javax.swing.JButton();
        JTUNES = new javax.swing.JButton();
        Word = new javax.swing.JButton();
        MEDIA1 = new javax.swing.JButton();
        CMD = new javax.swing.JButton();
        Twitter = new javax.swing.JButton();
        Hora = new javax.swing.JLabel();
        Fecha = new javax.swing.JLabel();
        OPCWINBUTTON = new javax.swing.JPanel();
        CREARUSER = new javax.swing.JButton();
        OFF = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        WIN = new javax.swing.JButton();
        fondoHome = new javax.swing.JLabel();
        Login = new javax.swing.JPanel();
        PASSFIELD = new javax.swing.JPasswordField();
        salir = new javax.swing.JButton();
        LOGBTN = new javax.swing.JButton();
        USERFIELD = new javax.swing.JTextField();
        UsuarioLabel = new javax.swing.JLabel();
        ContraLabel1 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        fondoLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WholeDesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraTareas.setBackground(new java.awt.Color(0, 0, 0));
        BarraTareas.setLayout(new java.awt.GridBagLayout());

        FILES.setBackground(new java.awt.Color(0, 0, 0));
        FILES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/exploradoricon_.jpg"))); // NOI18N
        FILES.setPreferredSize(new java.awt.Dimension(80, 60));
        FILES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FILESActionPerformed(evt);
            }
        });
        BarraTareas.add(FILES, new java.awt.GridBagConstraints());

        JTUNES.setBackground(new java.awt.Color(0, 0, 0));
        JTUNES.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/musicaicon_.jpg"))); // NOI18N
        JTUNES.setToolTipText("MP3");
        JTUNES.setPreferredSize(new java.awt.Dimension(80, 60));
        JTUNES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTUNESActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        BarraTareas.add(JTUNES, gridBagConstraints);

        Word.setBackground(new java.awt.Color(0, 0, 0));
        Word.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/_wordicon.jpg"))); // NOI18N
        Word.setPreferredSize(new java.awt.Dimension(80, 60));
        Word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        BarraTareas.add(Word, gridBagConstraints);

        MEDIA1.setBackground(new java.awt.Color(0, 0, 0));
        MEDIA1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/visor_.jpg"))); // NOI18N
        MEDIA1.setPreferredSize(new java.awt.Dimension(80, 60));
        MEDIA1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEDIA1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        BarraTareas.add(MEDIA1, gridBagConstraints);

        CMD.setBackground(new java.awt.Color(0, 0, 0));
        CMD.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/cmdicon_.jpg"))); // NOI18N
        CMD.setPreferredSize(new java.awt.Dimension(80, 60));
        CMD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CMDActionPerformed(evt);
            }
        });
        BarraTareas.add(CMD, new java.awt.GridBagConstraints());

        Twitter.setBackground(new java.awt.Color(0, 0, 0));
        Twitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/twitter.jpg"))); // NOI18N
        Twitter.setPreferredSize(new java.awt.Dimension(80, 60));
        Twitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TwitterActionPerformed(evt);
            }
        });
        BarraTareas.add(Twitter, new java.awt.GridBagConstraints());

        Hora.setText("00:00");
        BarraTareas.add(Hora, new java.awt.GridBagConstraints());

        Fecha.setText("0/0/0000");
        BarraTareas.add(Fecha, new java.awt.GridBagConstraints());

        WholeDesktop.add(BarraTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1000, 1860, 60));

        OPCWINBUTTON.setBackground(new java.awt.Color(51, 51, 255));
        OPCWINBUTTON.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        CREARUSER.setBackground(new java.awt.Color(0, 0, 0));
        CREARUSER.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/nuevousuarios_.jpg"))); // NOI18N
        CREARUSER.setPreferredSize(new java.awt.Dimension(160, 41));
        CREARUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREARUSERActionPerformed(evt);
            }
        });

        OFF.setBackground(new java.awt.Color(0, 0, 0));
        OFF.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/apagaricon_.jpg"))); // NOI18N
        OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFActionPerformed(evt);
            }
        });

        LOGOUT.setBackground(new java.awt.Color(0, 0, 0));
        LOGOUT.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/saliricon_.jpg"))); // NOI18N
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OPCWINBUTTONLayout = new javax.swing.GroupLayout(OPCWINBUTTON);
        OPCWINBUTTON.setLayout(OPCWINBUTTONLayout);
        OPCWINBUTTONLayout.setHorizontalGroup(
            OPCWINBUTTONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CREARUSER, javax.swing.GroupLayout.DEFAULT_SIZE, 154, Short.MAX_VALUE)
            .addComponent(OFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LOGOUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OPCWINBUTTONLayout.setVerticalGroup(
            OPCWINBUTTONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OPCWINBUTTONLayout.createSequentialGroup()
                .addComponent(CREARUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OFF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        WholeDesktop.add(OPCWINBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 840, 160, 160));

        WIN.setBackground(new java.awt.Color(0, 0, 0));
        WIN.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/windosicon_.jpg"))); // NOI18N
        WIN.setToolTipText("");
        WIN.setPreferredSize(new java.awt.Dimension(80, 60));
        WIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WINActionPerformed(evt);
            }
        });
        WholeDesktop.add(WIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1000, 70, -1));

        fondoHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HOME/fondo.jpg"))); // NOI18N
        WholeDesktop.add(fondoHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(WholeDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        Login.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Login.add(PASSFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 610, 330, 50));

        salir.setBackground(new java.awt.Color(0, 0, 0));
        salir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ImagenesDesktop/apagaricon_.jpg"))); // NOI18N
        salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salirActionPerformed(evt);
            }
        });
        Login.add(salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(1800, 20, 110, 50));

        LOGBTN.setBackground(new java.awt.Color(255, 255, 255));
        LOGBTN.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        LOGBTN.setForeground(new java.awt.Color(0, 0, 0));
        LOGBTN.setText("Iniciar sesión");
        LOGBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGBTNActionPerformed(evt);
            }
        });
        Login.add(LOGBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 700, 180, 40));
        Login.add(USERFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 510, 330, 50));

        UsuarioLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        UsuarioLabel.setForeground(new java.awt.Color(255, 255, 255));
        UsuarioLabel.setText("Usuario:");
        Login.add(UsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 510, 100, 50));

        ContraLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ContraLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ContraLabel1.setText("Contraseña:");
        Login.add(ContraLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 610, 100, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HOME/logo-windows-noir.png"))); // NOI18N
        Login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 10, 540, 490));

        fondoLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/HOME/fondo.jpg"))); // NOI18N
        Login.add(fondoLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        setLocation(new java.awt.Point(0, 0));
    }// </editor-fold>//GEN-END:initComponents

    private void WINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WINActionPerformed
        //Permite abrr y cerrar el boton de WIN con presionar este mismo.
        if (contBotonWin % 2 == 1) {
            OPCWINBUTTON.setVisible(false);
        } else {
            OPCWINBUTTON.setVisible(true);
        }
        contBotonWin++;


    }//GEN-LAST:event_WINActionPerformed

    private void FILESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FILESActionPerformed

        if (filesAdded) {
            try {
                WholeDesktop.add(files);
            } catch (Exception i) {
                System.out.println(i.getMessage());
            }
        }

        if (contBotonFiles % 2 == 1) {
            files.setVisible(false);
        } else {
            files.setVisible(true);
        }
        contBotonFiles++;
        filesAdded = false;
    }//GEN-LAST:event_FILESActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed

        WholeDesktop.setVisible(false);
        Login.setVisible(true);
        OPCWINBUTTON.setVisible(false);


    }//GEN-LAST:event_LOGOUTActionPerformed

    private void JTUNESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTUNESActionPerformed
        if (tunesAdded) {
            try {
                WholeDesktop.add(tunes);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        if (contBotonJtunes % 2 == 1) {
            tunes.setVisible(false);
        } else {
            tunes.setVisible(true);
        }

        contBotonJtunes++;
        tunesAdded = false;
    }//GEN-LAST:event_JTUNESActionPerformed

    private void OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFFActionPerformed
        System.exit(0);

    }//GEN-LAST:event_OFFActionPerformed

    private void CREARUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREARUSERActionPerformed
        if (userCreated) {
            try {
                WholeDesktop.add(create);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }

        if (LoggedUser.equalsIgnoreCase("Default")) {
            create.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(OPCWINBUTTON, "Solamente el usuario administrador puede realizar esta accion");
        }
        userCreated = false;
    }//GEN-LAST:event_CREARUSERActionPerformed

    private void CMDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CMDActionPerformed
        if (cmdAdded) {
            try {
                WholeDesktop.add(Cmd);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        if (contBotonCmd % 2 == 1) {
            Cmd.setVisible(false);
        } else {
            Cmd.setVisible(true);
        }

        contBotonCmd++;
        cmdAdded = false;
    }//GEN-LAST:event_CMDActionPerformed

    private void ArbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTree1FocusGained


    }//GEN-LAST:event_jTree1FocusGained

    private void LOGBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGBTNActionPerformed

        LoggedUser = USERFIELD.getText();
        pass = PASSFIELD.getText();
        files.nombre = this.USERFIELD.getText();
        files.tipo = this.USERFIELD.getText();

        try {
            if ((LoggedUser.equals("Default") && pass.equals("Default")) || create.LogInAcc(LoggedUser, pass)) {
                Login.setVisible(false);
                USERFIELD.setText("");
                PASSFIELD.setText("");
                WholeDesktop.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña invalidos");
            }
        } catch (IOException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_LOGBTNActionPerformed

    private void WordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WordActionPerformed

        if (wordAdded) {
            try {
                WholeDesktop.add(word);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        if (contBotonWord % 2 == 1) {
            word.setVisible(false);
        } else {
            word.setVisible(true);
        }
        contBotonWord++;
        wordAdded = false;
    }//GEN-LAST:event_WordActionPerformed

    private void MEDIA1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEDIA1ActionPerformed
        if (imagesAdded) {
            try {
                WholeDesktop.add(img);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        if (contBotonImages % 2 == 1) {
            img.setVisible(false);
        } else {
            img.setVisible(true);
        }
        contBotonImages++;
        imagesAdded = false;
    }//GEN-LAST:event_MEDIA1ActionPerformed

    private void TwitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TwitterActionPerformed
        if (twitAdded) {
            try {
                WholeDesktop.add(twit);
            } catch (Exception i) {
                System.out.println(i.getMessage());
            }
        }

        if (contBotonTwit % 2 == 1) {
            twit.setVisible(false);
        } else {
            twit.setVisible(true);
        }
        contBotonTwit++;
        twitAdded = false;
    }//GEN-LAST:event_TwitterActionPerformed

    private void salirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_salirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Desktop().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }

    private void actualizarHora() {
        Timer timer = new Timer(1000, (ActionEvent e) -> {
            Date ahora = new Date();
            SimpleDateFormat formatoHora = new SimpleDateFormat("HH:mm:ss");
            String horaFormateada = formatoHora.format(ahora);
            Hora.setText(horaFormateada);
        });
        timer.start();
    }

    private void actualizarFecha() {
        Timer timer = new Timer(1000, (ActionEvent e) -> {
            Date dia = new Date();
            SimpleDateFormat formatoDia = new SimpleDateFormat("dd/MM/yyyy");
            String diaactual = formatoDia.format(dia);
            Fecha.setText(diaactual);
        });
        timer.start();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTareas;
    private javax.swing.JButton CMD;
    private javax.swing.JButton CREARUSER;
    private javax.swing.JLabel ContraLabel1;
    private javax.swing.JButton FILES;
    private javax.swing.JLabel Fecha;
    private javax.swing.JLabel Hora;
    private javax.swing.JButton JTUNES;
    private javax.swing.JButton LOGBTN;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JPanel Login;
    private javax.swing.JButton MEDIA1;
    private javax.swing.JButton OFF;
    private javax.swing.JPanel OPCWINBUTTON;
    private javax.swing.JPasswordField PASSFIELD;
    private javax.swing.JButton Twitter;
    private javax.swing.JTextField USERFIELD;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JButton WIN;
    private javax.swing.JDesktopPane WholeDesktop;
    private javax.swing.JButton Word;
    private javax.swing.JLabel fondoHome;
    private javax.swing.JLabel fondoLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton salir;
    // End of variables declaration//GEN-END:variables
}
