/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package HOME;

import BRAIN.FolderManager;
import Explorador.ExploradorDeArchivos;
import Programitas.CrearUs;
import ReproductorMusical.Jtunes;
import WORD.Editor;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import visualizador.Media;

/**
 *
 * @author Josue Gavidia
 */
public class Desktop extends javax.swing.JFrame {

    /**
     * Creates new form Fancy
     */
    //VARIABLES DE ESTA CLASE   
    public static String LoggedUser;
    public static String newUser;
    public static String pass;
    public static boolean filesAdded;
    public static boolean tunesAdded;
    public static boolean userCreated;
    public static boolean wordAdded;
    public static int refresh = 0;
    public static String nombre;
    FolderManager L = new FolderManager(LoggedUser);
    int contBotonWin = 2;
    public static int contBotonFiles = 2;
    public static int contBotonJtunes = 2;
    public static int contBotonWord = 2;

    public Desktop() throws IOException {
        filesAdded = true;
        tunesAdded = true;
        userCreated = true;
        wordAdded = true;
        initComponents();

        L.CrearZyAdmin();
        this.setExtendedState(MAXIMIZED_BOTH);
        WholeDesktop.setVisible(false);
        WholeDesktop.setSize(1920, 1080);
        Login.setVisible(true);
        Login.setSize(1920, 1080);

        tunes.setVisible(false);

        OPCWINBUTTON.setVisible(false);

    }

    Jtunes tunes = new Jtunes();
    ExploradorDeArchivos files = new ExploradorDeArchivos();
    CrearUs create = new CrearUs();
    Editor word = new Editor();
    Media img = new Media();

    //FIN DEL MP3
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        WholeDesktop = new javax.swing.JDesktopPane();
        BarraTareas = new javax.swing.JPanel();
        FILES = new javax.swing.JButton();
        JTUNES = new javax.swing.JButton();
        Word = new javax.swing.JButton();
        MEDIA = new javax.swing.JButton();
        OPCWINBUTTON = new javax.swing.JPanel();
        CREARUSER = new javax.swing.JButton();
        OFF = new javax.swing.JButton();
        LOGOUT = new javax.swing.JButton();
        WIN = new javax.swing.JButton();
        Login = new javax.swing.JPanel();
        LOGBTN = new javax.swing.JButton();
        USERFIELD = new javax.swing.JTextField();
        UsuarioLabel = new javax.swing.JLabel();
        ContraLabel1 = new javax.swing.JLabel();
        PASSFIELD = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WholeDesktop.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BarraTareas.setBackground(new java.awt.Color(51, 51, 255));
        BarraTareas.setLayout(new java.awt.GridBagLayout());

        FILES.setText("Files");
        FILES.setPreferredSize(new java.awt.Dimension(80, 60));
        FILES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FILESActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        BarraTareas.add(FILES, gridBagConstraints);

        JTUNES.setText("Jtunes");
        JTUNES.setToolTipText("MP3");
        JTUNES.setPreferredSize(new java.awt.Dimension(80, 60));
        JTUNES.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTUNESActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 5;
        gridBagConstraints.gridy = 0;
        BarraTareas.add(JTUNES, gridBagConstraints);

        Word.setText("Word");
        Word.setPreferredSize(new java.awt.Dimension(80, 60));
        Word.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WordActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 0;
        BarraTareas.add(Word, gridBagConstraints);

        MEDIA.setText("Media");
        MEDIA.setPreferredSize(new java.awt.Dimension(80, 60));
        MEDIA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MEDIAActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 7;
        gridBagConstraints.gridy = 0;
        BarraTareas.add(MEDIA, gridBagConstraints);

        WholeDesktop.add(BarraTareas, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 1000, 1850, 60));

        CREARUSER.setText("Crear Usuario");
        CREARUSER.setPreferredSize(new java.awt.Dimension(160, 41));
        CREARUSER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CREARUSERActionPerformed(evt);
            }
        });

        OFF.setText("Apagar");
        OFF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFFActionPerformed(evt);
            }
        });

        LOGOUT.setText("Cerrar Sesion");
        LOGOUT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGOUTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout OPCWINBUTTONLayout = new javax.swing.GroupLayout(OPCWINBUTTON);
        OPCWINBUTTON.setLayout(OPCWINBUTTONLayout);
        OPCWINBUTTONLayout.setHorizontalGroup(
            OPCWINBUTTONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(CREARUSER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(OFF, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(LOGOUT, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        OPCWINBUTTONLayout.setVerticalGroup(
            OPCWINBUTTONLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(OPCWINBUTTONLayout.createSequentialGroup()
                .addComponent(CREARUSER, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(OFF, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LOGOUT, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(155, Short.MAX_VALUE))
        );

        WholeDesktop.add(OPCWINBUTTON, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 710, 160, 290));

        WIN.setText("W");
        WIN.setPreferredSize(new java.awt.Dimension(80, 60));
        WIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WINActionPerformed(evt);
            }
        });
        WholeDesktop.add(WIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 1000, 70, -1));

        getContentPane().add(WholeDesktop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        Login.setPreferredSize(new java.awt.Dimension(1920, 1080));
        Login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LOGBTN.setText("Iniciar sesion");
        LOGBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LOGBTNActionPerformed(evt);
            }
        });
        Login.add(LOGBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 590, 120, 40));
        Login.add(USERFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 400, 330, 50));

        UsuarioLabel.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        UsuarioLabel.setForeground(new java.awt.Color(0, 0, 0));
        UsuarioLabel.setText("Usuario");
        Login.add(UsuarioLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 400, 100, 50));

        ContraLabel1.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        ContraLabel1.setForeground(new java.awt.Color(0, 0, 0));
        ContraLabel1.setText("Contraseña");
        Login.add(ContraLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 470, 100, 50));
        Login.add(PASSFIELD, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, 330, 50));

        getContentPane().add(Login, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void WINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WINActionPerformed
        //Permite abrr y cerrar el boton de WIN con presionar este mismo.
        if (contBotonWin % 2 == 1) {
            OPCWINBUTTON.setVisible(false);
        } else {
            OPCWINBUTTON.setVisible(true);
        }
        contBotonWin++;


    }//GEN-LAST:event_WINActionPerformed

    private void FILESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FILESActionPerformed

        if (filesAdded) {
            try {
                WholeDesktop.add(files);
            } catch (Exception i) {
                System.out.println(i.getMessage());
            }
        }

        if (contBotonFiles % 2 == 1) {
            files.setVisible(false);
        } else {
            files.setVisible(true);
        }
        contBotonFiles++;
        filesAdded = false;
    }//GEN-LAST:event_FILESActionPerformed

    private void LOGOUTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGOUTActionPerformed

        WholeDesktop.setVisible(false);
        Login.setVisible(true);
        OPCWINBUTTON.setVisible(false);


    }//GEN-LAST:event_LOGOUTActionPerformed

    private void JTUNESActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTUNESActionPerformed
        if (tunesAdded) {
            try {
                WholeDesktop.add(tunes);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }
        if (contBotonJtunes % 2 == 1) {
            tunes.setVisible(false);
        } else {
            tunes.setVisible(true);
        }

        contBotonJtunes++;
        tunesAdded = false;
    }//GEN-LAST:event_JTUNESActionPerformed

    private void OFFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFFActionPerformed
        System.exit(0);

    }//GEN-LAST:event_OFFActionPerformed

    private void CREARUSERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CREARUSERActionPerformed
        if (userCreated) {
            try {
                WholeDesktop.add(create);

            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }

        if (LoggedUser.equalsIgnoreCase("admin")) {
            create.setVisible(true);

        } else {
            JOptionPane.showMessageDialog(OPCWINBUTTON, "Solamente el usuario administrador puede realizar esta accion");
        }
        userCreated = false;
    }//GEN-LAST:event_CREARUSERActionPerformed

    private void MEDIAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MEDIAActionPerformed
       try{
           WholeDesktop.add(img);
           
       }catch(Exception e){
           System.out.println(e.getMessage());
       }
       img.setVisible(true);
    }//GEN-LAST:event_MEDIAActionPerformed

    private void ArbFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTree1FocusGained


    }//GEN-LAST:event_jTree1FocusGained

    private void LOGBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LOGBTNActionPerformed

        LoggedUser = USERFIELD.getText();
        pass = PASSFIELD.getText();
        files.nombre = this.USERFIELD.getText();
        files.tipo = this.USERFIELD.getText();

        try {
            if ((LoggedUser.equals("admin") && pass.equals("admin"))||create.LogInAcc(LoggedUser,pass)) {
                Login.setVisible(false);
                USERFIELD.setText("");
                PASSFIELD.setText("");
                WholeDesktop.setVisible(true);
            } else {
                JOptionPane.showMessageDialog(this, "Usuario o contraseña invalidos");
            }
        } catch (IOException ex) {
            Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_LOGBTNActionPerformed

    private void WordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WordActionPerformed

        if (wordAdded) {
            try {
                WholeDesktop.add(word);
            } catch (Exception e) {
                System.out.println(e.getMessage());
            }
        }

        if (contBotonWord % 2 == 1) {
            word.setVisible(false);
        } else {
            word.setVisible(true);
        }
        contBotonWord++;
        wordAdded = false;
    }//GEN-LAST:event_WordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Desktop.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Desktop().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(Desktop.class.getName()).log(Level.SEVERE, null, ex);
                }

            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BarraTareas;
    private javax.swing.JButton CREARUSER;
    private javax.swing.JLabel ContraLabel1;
    private javax.swing.JButton FILES;
    private javax.swing.JButton JTUNES;
    private javax.swing.JButton LOGBTN;
    private javax.swing.JButton LOGOUT;
    private javax.swing.JPanel Login;
    private javax.swing.JButton MEDIA;
    private javax.swing.JButton OFF;
    private javax.swing.JPanel OPCWINBUTTON;
    private javax.swing.JTextField PASSFIELD;
    private javax.swing.JTextField USERFIELD;
    private javax.swing.JLabel UsuarioLabel;
    private javax.swing.JButton WIN;
    private javax.swing.JDesktopPane WholeDesktop;
    private javax.swing.JButton Word;
    // End of variables declaration//GEN-END:variables
}
