package Twitter;

import java.io.IOException;
import javax.swing.JOptionPane;

public class TwitterForm extends javax.swing.JFrame {

    /**
     * Creates new form TwitterForm
     */
    Twitter twit = new Twitter();
    public static String user;
    public static String pass;
    public TwitterForm() {
       
        initComponents();
         this.setSize(1920, 1080);
         PanelCrearUsuario.setVisible(false);
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        UsernameLogin = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        PasswordLogin = new javax.swing.JPasswordField();
        BotonLogin = new javax.swing.JButton();
        Registro = new javax.swing.JToggleButton();
        PanelCrearUsuario = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        CrearUsuarioBoton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameLoginActionPerformed(evt);
            }
        });
        PanelLogin.add(UsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 131, -1));

        jLabel1.setText("LOGIN");
        PanelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, -1, -1));

        jLabel2.setText("Username:");
        PanelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, -1, -1));

        jLabel3.setText("Password:");
        PanelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, -1, -1));
        PanelLogin.add(PasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, 131, -1));

        BotonLogin.setText("Login");
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });
        PanelLogin.add(BotonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 530, -1, -1));

        Registro.setText("Registrarse");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        PanelLogin.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, -1, -1));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        PanelCrearUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Edad");
        PanelCrearUsuario.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 400, 110, 30));

        CrearUsuarioBoton.setText("Crear");
        CrearUsuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBotonActionPerformed(evt);
            }
        });
        PanelCrearUsuario.add(CrearUsuarioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, -1, -1));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre");
        PanelCrearUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 200, 90, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Genero");
        PanelCrearUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 90, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Nombre de Usuario");
        PanelCrearUsuario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 190, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Contraseña");
        PanelCrearUsuario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 330, 110, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Edad");
        PanelCrearUsuario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 110, 30));

        getContentPane().add(PanelCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1920, 1080));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void UsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameLoginActionPerformed

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonLoginActionPerformed

    private void CrearUsuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBotonActionPerformed
        // TODO add your handling code here:
        try {
            if (twit.crearCuenta("Hola", "bye", 'm', 93493434L, 19)) {
                JOptionPane.showMessageDialog(null, "Cuenta creada exitosamente");
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo crear la cuenta bruv");
            }

        } catch (IOException e) {
            System.out.println(e.getMessage());;
        }
        
        PanelCrearUsuario.setVisible(false);
        PanelLogin.setVisible(true);


    }//GEN-LAST:event_CrearUsuarioBotonActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
       PanelCrearUsuario.setVisible(true);
       PanelLogin.setVisible(false);
    }//GEN-LAST:event_RegistroActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TwitterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TwitterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TwitterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TwitterForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TwitterForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotonLogin;
    private javax.swing.JButton CrearUsuarioBoton;
    private javax.swing.JPanel PanelCrearUsuario;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPasswordField PasswordLogin;
    private javax.swing.JToggleButton Registro;
    private javax.swing.JTextField UsernameLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
