/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Twitter;

import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Josue Gavidia
 */
public class Twitt extends javax.swing.JInternalFrame {

    /**
     * Creates new form Twitt
     */
    Twitter twit = new Twitter();
    public String user,pass;
    public char gender;
    public int age;
    public Twitt() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PanelLogin = new javax.swing.JPanel();
        UsernameLogin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PasswordLogin = new javax.swing.JPasswordField();
        BotonLogin = new javax.swing.JButton();
        Registro = new javax.swing.JToggleButton();
        PanelCrearUsuario = new javax.swing.JPanel();
        CrearUsuarioBoton = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        USER = new javax.swing.JTextField();
        PASS = new javax.swing.JTextField();
        AGE = new javax.swing.JTextField();
        NAME = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel3 = new javax.swing.JLabel();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();

        PanelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        UsernameLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsernameLoginActionPerformed(evt);
            }
        });
        PanelLogin.add(UsernameLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 380, 131, -1));

        jLabel4.setText("LOGIN");
        PanelLogin.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 260, -1, -1));

        jLabel5.setText("Username:");
        PanelLogin.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 380, -1, -1));

        jLabel6.setText("Password:");
        PanelLogin.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 440, -1, -1));
        PanelLogin.add(PasswordLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 430, 131, -1));

        BotonLogin.setText("Login");
        BotonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonLoginActionPerformed(evt);
            }
        });
        PanelLogin.add(BotonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 530, -1, -1));

        Registro.setText("Registrarse");
        Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegistroActionPerformed(evt);
            }
        });
        PanelLogin.add(Registro, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 530, -1, -1));

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PanelCrearUsuario.setBackground(new java.awt.Color(255, 255, 255));
        PanelCrearUsuario.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        CrearUsuarioBoton.setText("Crear Usuario");
        CrearUsuarioBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearUsuarioBotonActionPerformed(evt);
            }
        });
        PanelCrearUsuario.add(CrearUsuarioBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 150, 70));

        jLabel8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Nombre");
        PanelCrearUsuario.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 90, 30));

        jLabel9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(0, 0, 0));
        jLabel9.setText("Genero");
        PanelCrearUsuario.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 90, 30));

        jLabel10.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(0, 0, 0));
        jLabel10.setText("Usuario");
        PanelCrearUsuario.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 80, 30));

        jLabel11.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 0, 0));
        jLabel11.setText("Contraseña");
        PanelCrearUsuario.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 290, 100, 30));

        jLabel12.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(0, 0, 0));
        jLabel12.setText("Edad");
        PanelCrearUsuario.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 360, 50, 30));

        USER.setBackground(new java.awt.Color(255, 255, 255));
        USER.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        USER.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                USERActionPerformed(evt);
            }
        });
        PanelCrearUsuario.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 220, 290, 40));

        PASS.setBackground(new java.awt.Color(255, 255, 255));
        PASS.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        PASS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PASSActionPerformed(evt);
            }
        });
        PanelCrearUsuario.add(PASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 280, 290, 40));

        AGE.setBackground(new java.awt.Color(255, 255, 255));
        AGE.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        PanelCrearUsuario.add(AGE, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 290, 40));

        NAME.setBackground(new java.awt.Color(255, 255, 255));
        NAME.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 102), 1, true));
        PanelCrearUsuario.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 290, 40));

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("PROFILE PIC");
        jLabel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        PanelCrearUsuario.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 110, 210, 180));

        jToggleButton1.setText("Escoger Foto");
        PanelCrearUsuario.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 340, 120, 60));

        jLabel3.setFont(new java.awt.Font("Arial", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 102));
        jLabel3.setText("REGISTRO");
        PanelCrearUsuario.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, -1, -1));

        jToggleButton2.setText("Masculino");
        PanelCrearUsuario.add(jToggleButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 160, 110, 40));

        jToggleButton3.setText("Femenino");
        PanelCrearUsuario.add(jToggleButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 160, 100, 40));

        getContentPane().add(PanelCrearUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 70, 760, 540));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Twitter/Fondo.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1430, 810));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CrearUsuarioBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearUsuarioBotonActionPerformed
        // TODO add your handling code here:
        try {
            if (twit.crearCuenta(USER.getText(), PASS.getText(), SEX.getText().charAt(0), 93493434L, 19)) {
                JOptionPane.showMessageDialog(null, "Cuenta creada exitosamente");
            }else{
                JOptionPane.showMessageDialog(null, "No se pudo crear la cuenta bruv");
            }

        } catch (IOException e) {
            System.out.println(e.getMessage());;
        }

        PanelCrearUsuario.setVisible(false);
        PanelLogin.setVisible(true);

    }//GEN-LAST:event_CrearUsuarioBotonActionPerformed

    private void USERActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_USERActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_USERActionPerformed

    private void PASSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PASSActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PASSActionPerformed

    private void UsernameLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsernameLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsernameLoginActionPerformed

    private void BotonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonLoginActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BotonLoginActionPerformed

    private void RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegistroActionPerformed
        PanelCrearUsuario.setVisible(true);
        PanelLogin.setVisible(false);
    }//GEN-LAST:event_RegistroActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AGE;
    private javax.swing.JButton BotonLogin;
    private javax.swing.JButton CrearUsuarioBoton;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField PASS;
    private javax.swing.JPanel PanelCrearUsuario;
    private javax.swing.JPanel PanelLogin;
    private javax.swing.JPasswordField PasswordLogin;
    private javax.swing.JToggleButton Registro;
    private javax.swing.JTextField USER;
    private javax.swing.JTextField UsernameLogin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    // End of variables declaration//GEN-END:variables
}
